# ============================================================
# MCP Name      : RSS_Feed_MCP
# Author        : Your Name
# Creation Date : 2025-10-26
# Description   : Configuration for the RSS Feed MCP server.
#                 Add, remove, or edit the RSS feeds you want
#                 the LLM to be able to check.
# ============================================================

# A list of RSS feeds to be monitored.
# Each feed needs a 'name' (for the LLM to refer to) and a 'url'.
feeds:
  - name: "BBC World News"
    url: "http://feeds.bbci.co.uk/news/world/rss.xml"

  - name: "Hacker News"
    url: "https://hnrss.org/frontpage"

  - name: "Wired Top Stories"
    url: "https://www.wired.com/feed/rss"

  - name: "The Verge"
    url: "https://www.theverge.com/rss/index.xml"